config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :organizations, path: 'organizations', controllers: {sessions: "organizations/sessions"}


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_applications, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:new, :index, :show, :edit, :update]
  resources :organizations, only: [:index, :show, :edit, :update]
  resources :jobs
  resources :profiles


  get 'organizations/:id/jobs', to: 'organizations#jobs'

  resources :jobs do
    resources :users, only: [:index]
  end
  resources :organizations do
    resources :jobs
  end
  post 'jobs/:id/apply', to: 'jobs#apply'

  root 'welcome#index'


  end

app/models/job.rb
class Job < ApplicationRecord
	has_many :job_users
	has_many :users, through: :job_users
	belongs_to :organization

	scope :recent, -> {order(created_at: :desc)}

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
	def index
		if params[:organization_id]
			@jobs =  Job.find(params(:organization_id)).jobs
		else
			@jobs = Job.all
		end
	end

	def new
		@org = Organization.find(params[:organization_id])
		@job = @org.jobs.build
	end

	def create
		@org = Organization.find(params[:organization_id])
		@job = @org.jobs.build(job_params)
		@job.save
		respond_to do |format|
			format.json { render json: {job: @job, org: @org}}
			format.html
		end
	end

	def show
		@job = Job.find(params[:id])
		@org = @job.organization
		respond_to do |format|
			format.json { render json: {job: @job, org: @org} }
			format.html
		end
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update(job_params)
		redirect_to job_path(@job)
	end

	def destroy
		@org = Organization.find(params[:organization_id])
		@job = Job.find(params[:id])
		@job.destroy
		render json: @org
	end

	def apply
		if current_user && !has_applied?(current_user, params[:id].to_i)
			@job = Job.find(params[:id])
			current_user.jobs_applied << @job
			current_user.save
			redirect_to current_user
		elsif current_user && has_applied?(current_user, params[:id].to_i)
			flash[:alert] = "You have already applied to this position."
			redirect_to jobs_path
		else
			session[:viewed_job] = params[:id]
			redirect_to new_user_session_path
		end
	end

	private

	def has_applied?(user, job)
		user.jobs_applied_ids.include?(job.to_i)
	end
	
	def job_params
		params.require(:job).permit(:title, :location, :description, :level, :salary, :organization_id)
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="newJobOverlay notVisible">

	<div class="col-sm-12 newJobModal">
		<h3>New Job Form</h3>

		<%= form_for [@org, @job] do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title %><br>
				
				<%= f.label :location %>
				<%= f.text_field :location %><br>
				
				<%= f.label :description %><br>
				<%= f.text_area :description %><br>
				
				<%= f.label :level %>
				<%= f.text_field :level %><br>
				
				<%= f.label :salary %>
				<%= f.text_field :salary %><br>
				
				<%= f.submit %>
			</div>
		<%end%>
		<p id="close">X</p></div>
		
</div>

app/views/jobs/_indexTemplate.html.erb
<script  type="text/x-handlebars-template" id="jobsShowPage">
	<br>
	<h3>Here's the info on that job</h3>
	<div class="col-sm-12">
		<h6>Title: {{title}}</h6>
		<p>Location: {{location}}</p>
		<p>Exp: {{level}}</p>
		<p>Salary: {{salary}}</p>
		<p>Description: {{description}}</p>
	</div>
	<a href="">Back</a>
</script>

app/views/jobs/edit.html.erb
<div style="">
<%= render partial: 'form' %>
</div>

app/views/jobs/index.html.erb
<div class="col-md-12">
	<h3>Open Jobs</h3><br>
	<div id="listedJobs">
		<% @jobs.each.with_index(1) do |job,i| %>
			<%= link_to "#{job.title}", job_path(job), class: "openJob" %><br>
			<%= job.location %><br>
			<%= truncate job.description %><br>
			<%= job.level %><br>
			<%= job.salary %><br>
			<hr class="jobsList">
		<%end%>
	</div>
</div>

app/views/jobs/new.html.erb
<%= render partial: 'form' %>

app/views/jobs/show.html.erb
<div class="row">
	<div class="col-md-12">
	<h3><%= @job.title %></h3>
	<h5>@</h5>
	</div>
</div>

<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<ul>
			<li><%= @job.organization.name %><br><h5>In</h5></li>
			<li><%= @job.location  %> </li>
			<li><strong>Description</strong>:<br><%=@job.description  %></li>
			<li><strong>Experience Level</strong>:<br><%= @job.level  %> </li>
			<li><%= @job.salary %> </li>
		</ul>
	</div>
	<div class="col-md-4"></div>
</div>

<div class="row">
	<% if current_user.present? %>
		<div class="col-md-12">
			<small>Learn about <%= link_to "#{@job.organization.name}", organization_path(@org) %></small><br>
			<%= link_to "Back", :back %> | <%= link_to "My Profile", user_path(current_user) %><br><br>
			<%= button_to "Apply", class: "btn btn-primary", action: "apply" %>
		</div>
	<%elsif !current_user.present? && !current_organization.present?%>
		<div class="col-md-12">
			<%= link_to "Back", :back %> | <%= button_to "Apply", action: "apply" %>
		</div>
	<%else%>
	<div class="col-md-12">
		<%= link_to "View Applicants", job_users_path(@job)  %><br>
		<%= link_to "Edit Position", edit_organization_job_path(@org,@job), id: "editJob"%><br>
		<%= link_to "Back", organization_jobs_path(@job) %>
		
		<%= render partial: 'form' %>
	</div> 
	<%end%>
</div>