config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :organizations, path: 'organizations', controllers: {sessions: "organizations/sessions"}


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_applications, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:new, :index, :show, :edit, :update]
  resources :organizations, only: [:index, :show, :edit, :update]
  resources :jobs
  resources :profiles


  get 'organizations/:id/jobs', to: 'organizations#jobs'

  resources :jobs do
    resources :users, only: [:index]
  end
  resources :organizations do
    resources :jobs
  end
  post 'jobs/:id/apply', to: 'jobs#apply'

  root 'welcome#index'


  end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable, :omniauthable,
	:omniauth_providers => [:google_oauth2]
	
	has_many :job_users
	has_many :jobs_applied, through: :job_users, source: "job"
	has_one :job_application
	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
	
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2

     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env['omniauth.auth'])

     if @user.persisted?
       flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
       sign_in_and_redirect @user, event: :authentication
     else
       session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
       redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
     end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
     unless user
         user = User.create(
           email: data['email'],
            password: Devise.friendly_token[0,20]
         )
    end
    user
end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		if params[:job_id]
			@job = Job.find(params[:job_id])
			@users = Job.find(params[:job_id]).users
		else
			@users = User.all
		end
	end


	def new
		render layout: false
	end
	
	def create
		if @user.save
			redirect_to @user
		end
	end
	
	def show
		@user = User.find(params[:id])
		@profile = @user.job_application.profile unless @user.job_application.nil?
		@jobs_applied = @user.jobs_applied
	end
	
	def edit
		@user = current_user
	end

	def update
		@user = current_user
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	private
	
		def user_params
			params.require(:user).permit(:user_photo, :job_application_attributes => [:first_name, :middle_name, :last_name, :address, :city, :state, :zip_code, :phone])
		end
	
end

app/views/users/_profile_absent.html.erb
<div class="signUpForm">
<p>Complete your profile and application to start applying for jobs.</p>

  <%= link_to "Click to complete your application", new_job_application_path %><br>
</div>

app/views/users/_profile_present.html.erb
<%= profile.full_name %><br>
<%= profile.phone %><br>
<%= user.email %><br><br>
<% if current_user === @user %>
	<%= link_to "Edit Application", edit_job_application_path%><br><br>
<%else%>
	<%= link_to "Back", :back %>
<%end%>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>



<%= fields_for :job_application, @user.job_application do |job_app| %>
  <%= job_app.label :first_name %>
  <%= job_app.text_field :first_name %><br>

  <%= job_app.submit %>

  <%end%>
<%end%>

app/views/users/index.html.erb
<div class="col-sm-12">
<h3>Applicants for Job: <%= @job.title %></h3><br>
</div>
<div class="col-sm-12">
	<% if @users.size >= 1 %>
<% @users.each.with_index(1) do |user,i| %>
  <p><%= "#{i}. "%><%= link_to user.job_application.profile.full_name, user %> | <%= user.email %></p>
	<%end%>
	 <%= link_to "Back", organization_job_path(@job.organization, @job) %>
	<%else%>
	<p>There are no applications for this postiion.</p>
		<%= link_to "Back", organization_job_path(@job.organization, @job) %>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="col-md-6">
	<% if current_user === @user %>
	<div class="image-place" style="">
		<% if @user.job_application.present? && @user.job_application.profile.present? %>
			<% if @profile.user_photo.present? %>
			<%= image_tag @profile.user_photo.url(:medium) %>
			<%end%>
		<%end%>
	</div><br>
	<%end%>
	
	<% if current_user %>
		<h5>Your Application</h5>
		<% if @user.job_application.present? && @user.job_application.profile.present? %>
			<%= render partial: 'users/profile_present', locals: {profile: @profile, user: @user} %>
			<%else%>
			<%= render partial: 'users/profile_absent', locals: {user: @user} %>
		<%end%>
	<% elsif current_organization %>
		<div class="col-md-12 signUpForm" style="margin-left:50%;">
		<h5>Applicant</h5>
		<%= render partial: 'users/profile_present', locals: {profile: @profile, user: @user} %>
	</div>
	
	<%end%>

</div>

<% if current_user && current_user.job_application.present? %>
<div class="col-md-4">
	<div class="jobs_applied"><br>
		<h2>Your Jobs</h2><br>
		<% if @jobs_applied.size >= 1 %>
			<% @jobs_applied.each.with_index(1) do |job, i| %>
				<%= link_to job.title, job_path(job), class: "jobShow" %> @
				<%= job.organization.name %><br>
				 You applied <%= time_ago_in_words(job.created_at) %> ago<br>
				<hr id="appliedJobsList">
			<%end%>
		<%else%>
			<h5>You have not applied to any jobs</h5>
		<%end%>
	</div>
<%end%>
</div>