config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :organizations, path: 'organizations', controllers: {sessions: "organizations/sessions"}


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :job_applications, only: [:new, :create, :show, :edit, :update]
  resources :users, only: [:new, :index, :show, :edit, :update]
  resources :organizations, only: [:index, :show, :edit, :update]
  resources :jobs
  resources :profiles


  get 'organizations/:id/jobs', to: 'organizations#jobs'

  resources :jobs do
    resources :users, only: [:index]
  end
  resources :organizations do
    resources :jobs
  end
  post 'jobs/:id/apply', to: 'jobs#apply'

  root 'welcome#index'


  end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :job_users
	has_many :users, through: :job_users
	belongs_to :organization

	scope :recent, -> {order(created_at: :desc)}

end

app/models/job_application.rb
class JobApplication < ApplicationRecord
	belongs_to :user
	has_one :profile

	def profile_attributes=(attributes)
		if self.profile.present?
			self.profile.update(attributes)
		else
			self.build_profile(attributes)
			self.save
		end
	end
	
end

app/models/job_user.rb
class JobUser < ApplicationRecord
	belongs_to :user
	belongs_to :job
end

app/models/organization.rb
class Organization < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
  has_one :profile



	def org_profile
		{:name => self.name, :location => self.location, :email => self.email}.compact
	end
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :addresses
	belongs_to :job_application

	has_attached_file :user_photo, default_url: ':style/default.png', styles: {medium: "200x200>", thumb: "100x100>" }
	validates_attachment_content_type :user_photo, content_type: /\Aimage\/.*\z/

	def full_name
		"#{self.first_name} #{self.middle_name} #{self.last_name}"
	end

	def city_state
	end
	
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable, :omniauthable,
	:omniauth_providers => [:google_oauth2]
	
	has_many :job_users
	has_many :jobs_applied, through: :job_users, source: "job"
	has_one :job_application
	
	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = auth.info.email
			user.password = Devise.friendly_token[0,20]
		end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :store_user_location!, if: :storable_location?
	
	def after_sign_in_path_for(resource)
		resource
	end
	
	private
		def storable_location?
			request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
		end
		
		def store_user_location!
			# :user is the scope we are authenticating
			store_location_for(:user, request.fullpath)
		end
		
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	
	def index
		if params[:organization_id]
			@jobs =  Job.find(params(:organization_id)).jobs
		else
			@jobs = Job.all
		end
	end

	def new
		@org = Organization.find(params[:organization_id])
		@job = @org.jobs.build
	end

	def create
		@org = Organization.find(params[:organization_id])
		@job = @org.jobs.build(job_params)
		@job.save
		respond_to do |format|
			format.json { render json: {job: @job, org: @org}}
			format.html
		end
	end

	def show
		@job = Job.find(params[:id])
		@org = @job.organization
		respond_to do |format|
			format.json { render json: {job: @job, org: @org} }
			format.html
		end
	end

	def edit
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		@job.update(job_params)
		redirect_to job_path(@job)
	end

	def destroy
		@org = Organization.find(params[:organization_id])
		@job = Job.find(params[:id])
		@job.destroy
		render json: @org
	end

	def apply
		if current_user && !has_applied?(current_user, params[:id].to_i)
			@job = Job.find(params[:id])
			current_user.jobs_applied << @job
			current_user.save
			redirect_to current_user
		elsif current_user && has_applied?(current_user, params[:id].to_i)
			flash[:alert] = "You have already applied to this position."
			redirect_to jobs_path
		else
			session[:viewed_job] = params[:id]
			redirect_to new_user_session_path
		end
	end

	private

	def has_applied?(user, job)
		user.jobs_applied_ids.include?(job.to_i)
	end
	
	def job_params
		params.require(:job).permit(:title, :location, :description, :level, :salary, :organization_id)
	end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	def index
	
	end
	
	def show
		@org = Organization.find(params[:id])
		@org_profile = @org.org_profile
	end
	
	def jobs
		@org = current_organization
		@jobs = current_organization.jobs
		@job = Job.new
	end
	
	def edit
		@org = Organization.find(params[:id])
	end

	def update
		@org = Organization.find(params[:id])
		@org.update(org_params)
		redirect_to organization_path(@org)
	end

	private
	
		def org_params
			params.require(:organization).permit(:name, :location, :email)
		end
		
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new
		@profile = Profile.new
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		if params[:job_id]
			@job = Job.find(params[:job_id])
			@users = Job.find(params[:job_id]).users
		else
			@users = User.all
		end
	end


	def new
		render layout: false
	end
	
	def create
		if @user.save
			redirect_to @user
		end
	end
	
	def show
		@user = User.find(params[:id])
		@profile = @user.job_application.profile unless @user.job_application.nil?
		@jobs_applied = @user.jobs_applied
	end
	
	def edit
		@user = current_user
	end

	def update
		@user = current_user
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	private
	
		def user_params
			params.require(:user).permit(:user_photo, :job_application_attributes => [:first_name, :middle_name, :last_name, :address, :city, :state, :zip_code, :phone])
		end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_application_helper.rb
module JobApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_logged_in_nav.html.erb
<nav class="nav nav-pills flex-column flex-sm-row">


  <% if current_user  %>
    <%= link_to "My Profile", current_user, class:"flex-sm-fill text-sm-center nav-link " %>

    <%= link_to "Jobs", jobs_path, class: "nav-link jobsIndex" %>

    <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", :method => :delete %>

  <%elsif current_organization%>
    <%= link_to "Organization Profile", current_organization, class:"flex-sm-fill text-sm-center nav-link " %>

    <%= link_to "Sign out", destroy_organization_session_path, class:"flex-sm-fill text-sm-center nav-link ",  :method => :delete %>



  <%end%>


</nav>

app/views/layouts/_messages.html.erb
<div id="noticeFlashes" >

<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
 <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
 <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
</div>

app/views/layouts/_navigation.html.erb
        <nav class="nav nav-pills flex-column flex-sm-row">
          <% if current_user.nil? && current_organization.nil? %>
          <%= link_to "Home", root_path, class:"btn btn-primary flex-sm-fill text-sm-center nav-link " %>

          <%= link_to "Seeker", new_user_session_path, class:"btn btn-primary flex-sm-fill text-sm-center nav-link" %>

          <%= link_to "Employer", new_organization_session_path, class:"btn btn-primary flex-sm-fill text-sm-center nav-link " %>

           <%else%>

           <%= render 'layouts/logged_in_nav' %>

          <%end%>


        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Vakant</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
		 integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
		 crossorigin="anonymous" />
  </head>

  <body>
    <header>
      <div class="container">
        <div class="row">
      	<%= render 'layouts/navigation' %>
    		</div>
    	</div>
    </header>
    <%= render partial: 'layouts/messages' %>
    <div class="container">
      
      <div class="row main">
      	<%= yield %>
    	</div>
    </div>
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="output">
					</div>
				</div>
			</div>
		</div>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>
		<%= render partial: '../views/jobs/indexTemplate' %>
  </body>
</html>